# Generated by Django 3.2.5 on 2022-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('song_genre', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
            ],
        ),
    ]
