# Generated by Django 4.1.5 on 2023-04-26 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20220213_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
