# Generated by Django 4.1.5 on 2023-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='documents'),
        ),
    ]
